[package]
authors = ["Matt Taylor <mstaveleytaylor@gmail.com>"]
edition = "2018"
name = "rt"
version = "0.1.0"

[dependencies]
derive-new = "0.5.6"
image = "0.21.0"
num = "0.2.0"
rayon = "1.0.3"
rand = "0.6.5"
