[package]
authors = ["Matt Taylor <mstaveleytaylor@gmail.com>"]
edition = "2018"
name = "rt"
version = "0.1.0"

[dependencies]
derive-new = "0.5.6"
image = "0.21.0"
nalgebra = "0.17.2"
num = "0.2.0"
rand = "0.6.5"
rayon = "1.0.3"
bvh = "0.3.1"
indicatif = "0.11.0"
